server:
  port: 8089
  error:
    include-exception: false
    include-message: always
    include-stacktrace: ON_PARAM
    whitelabel:
      enabled: true

oftpserver:
  base_directory: cepaas-oftp2-server/src/main/resources/serverdir
  port: 16619
  tls_yn: true
  keystorePath : cepaas-oftp2-server/src/main/resources/keys/priv.jks
  keystorePassword : "#*.cloudedi.net@"
  ssid : NH_SSID
  password : NHPASS
  physicalPartners:
  - partnerSsId: MENDELSON_SSID
    hostName: localhost
    partnerIpPort: 6619
    partnerSslYn: true
    partnerSslCertPath: cepaas-oftp2-server/src/main/resources/keys/mendelson_key.cer
  logicalPartners:
  - partnerSfId: MENDELSON_SFID
    partnerSsId: MENDELSON_SSID
    partnerFileEncryptCertPath: cepaas-oftp2-server/src/main/resources/keys/mendelson_key.cer
    partnerFileSigningCertPath: cepaas-oftp2-server/src/main/resources/keys/mendelson_key.cer
    partnerEerpSigningCertPath: cepaas-oftp2-server/src/main/resources/keys/mendelson_key.cer
    messageBoxId: 691650f0-b19e-11ed-9d18-0242ac130002
    messageBoxEndPoint: http://localhost:8181
    outBoundSlotId: 
    inBoundSlotId: b0818ecb-b1c3-11ed-b586-0242ac130002
    charEncoding: UTF-8
    signedEerpRequestYn: false
    fileCompressionYn: false
    fileEncryptionYn: false
    fileSignYn: false
  - partnerSfId: NH_SFID
    partnerSsId: NH_SSID
    partnerFileEncryptCertPath: cepaas-oftp2-server/src/main/resources/keys/inspien.cer
    partnerFileSigningCertPath: cepaas-oftp2-server/src/main/resources/keys/inspien.cer
    partnerEerpSigningCertPath: cepaas-oftp2-server/src/main/resources/keys/inspien.cer
    messageBoxId: 691650f0-b19e-11ed-9d18-0242ac130002
    messageBoxEndPoint: http://localhost:8181
    outBoundSlotId: 90aaabea-b1c3-11ed-b586-0242ac130000
    inBoundSlotId: 
    charEncoding: UTF-8
    signedEerpRequestYn: false
    fileCompressionYn: false
    fileEncryptionYn: false
    fileSignYn: false
