server:
  port: 8089
  error:
    include-exception: false
    include-message: always
    include-stacktrace: ON_PARAM
    whitelabel:
      enabled: true

oftpserver:
  base_directory: cepaas-oftp2-server/src/main/resources/serverdir
  port: 16619
  tls_yn: true
  keystorePath : cepaas-oftp2-server/src/main/resources/keys/priv.jks
  keystorePassword : "#*.cloudedi.net@"
  ssid : NH_SSID
  password : NHPASS

# oftpclient:
#   to:
#     inboundSlot: 983293fd-cb00-469c-a4f2-72d33a005671
#   vfOption:
#     partnerSignCertPath: src/test/resources/oftpService/key/mendelson4key.cer
#     partnerKeystorePath: src/test/resources/oftpService/key/priv.jks
#     partnerKeystorePassword: "#*.cloudedi.net@"
#   downLoadOption:
#     sourceEncoding: UTF-8
#     base64Encode:
#       use: true
#       pattern: .*BASE64.*
oftppartners:
  partnerkeys:
    - partnerName: mendelson1
      partnerSignCertPath: src/test/resources/oftpService/key/mendelson4key.cer
      partnerKeystorePath: src/test/resources/oftpService/key/priv.jks
      partnerKeystorePassword: "#*.cloudedi.net@"
    - partnerName: mendelson2
      partnerSignCertPath: src/test/resources/oftpService/key/mendelson4key.cer
      partnerKeystorePath: src/test/resources/oftpService/key/priv.jks
      partnerKeystorePassword: "#*.cloudedi.net@"
    - partnerName: mendelson
      partnerSignCertPath: src/test/resources/oftpService/key/mendelson4key.cer
      partnerKeystorePath: src/test/resources/oftpService/key/priv.jks
      partnerKeystorePassword: "#*.cloudedi.net@"